// 表格表头的数据检验订单详情的送检单信息
import {
  handPeriodTypeDict,
  packetStateArr,
  qcTypeArr,
  qcTypeDict,
  packetStateDict,
  handPeriodTypeArr,
  startCollectorTypeArr,
  experimentContentArr,
  seqInstrumentArr,
} from '@/utils/experimentServiceDict';
import moment from 'moment';
// 首页的
export const tableHomeColumns = [
  {
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '技术路线编码',
    dataIndex: 'code',
  },
  {
    title: '技术路线名称',
    dataIndex: 'name',
  },
  {
    title: '状态',
    dataIndex: 'state',
    render: val => <span>{packetStateDict[val]}</span>,
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    render: val => <span>{handPeriodTypeDict[val]}</span>,
  },
  {
    title: '启动样本类型',
    dataIndex: 'sampleTypeId',
  },
  {
    title: '质控流程',
    dataIndex: 'qcType',
    render: val => <span>{qcTypeDict[val]}</span>,
  },
  {
    title: '备注',
    dataIndex: 'remark',
  },
  {
    title: '最后更新人',
    dataIndex: 'modifyPerson',
  },
  {
    title: '最后更新时间',
    dataIndex: 'modifyTime',
    render: val => <span>{val? moment(val).format('YYYY-MM-DD HH:mm:ss') : ''}</span>,
  },
  {
    title: '创建人',
    dataIndex: 'createPerson',
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    render: val => <span>{val? moment(val).format('YYYY-MM-DD HH:mm:ss') : ''}</span>,
  },
];
// 添加页输入的数据
export const fieldLabelsForm = [
  {
    key: 'code',
    label: '技术路线编码',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'name',
    label: '技术路线名称',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'qcType',
    label: '质控流程',
    disabled: false,
    value: [],
    mode: 'multiple',
    require: false,
    type: 'select',
    selectArr: qcTypeArr,
  },
  {
    key: 'seqInstrument',
    label: '支持技术平台',
    disabled: false,
    value: '',
    require: true,
    mode: 'multiple',
    type: 'select',
    selectArr: seqInstrumentArr,
  },
  {
    key: 'remark',
    label: '备注',
    disabled: false,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'handPeriod',
    label: '交付周期',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'handPeriodType',
    label: '交付日类型',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: handPeriodTypeArr,
  },
  {
    key: 'state',
    label: '状态',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: packetStateArr,
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
];
// 添加页的表格表头的样本信息
export const tableAddSampleColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '启动样本类型',
    dataIndex: 'sampleTypeId',
    disabled: false,
    value: '',
    require: true,
    mode: '',
    type: 'select',
    selectArr: [],
  },
  {
    title: '启动管型',
    dataIndex: 'startCollectorType',
    disabled: false,
    value: '',
    require: true,
    mode: '',
    type: 'select',
    selectArr: startCollectorTypeArr,
  },
  {
    title: '起始量',
    dataIndex: 'volume',
    disabled: false,
    value: '',
    validateType: 'number_2', // 校验类型
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    title: '单位',
    dataIndex: 'unit',
    disabled: false,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
];

// 添加页的表格表头的流程节点
export const tableAddFlowColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '工序编号',
    dataIndex: 'code',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '工序名称',
    dataIndex: 'name',
    disabled: false,
    value: '',
    require: true,
    type: 'select-input',
    childKey: 'handPeriod', // 级联的关联字段
    selectArr: [],
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: 'QC检测内容',
    dataIndex: 'qcExamContent',
    disabled: false,
    value: '',
    require: false,
    mode: 'multiple',
    type: 'select',
    selectArr: experimentContentArr,
  },
  // {
  //   title: '中间产物类型',
  //   dataIndex: 'middleSampleTypeId',
  //   disabled: false,
  //   value: '',
  //   require: false,
  //   mode: 'multiple',
  //   type: 'select',
  //   selectArr: [],
  // },
];
// 详情页的
