// 工艺方法主界面
// 引入字典

import moment from 'moment';
import { packetStateDict, packetStateArr } from '@/utils/experimentServiceDict';
//表格数据
export const tableHomeColumns = [
  {
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '工序方法编码',
    dataIndex: 'code',
  },
  {
    title: '工序方法名称',
    dataIndex: 'name',
  },
  {
    title: '所属工序编码',
    dataIndex: 'processCode',
  },
  {
    title: '所属工序名称',
    dataIndex: 'processName',
  },
  {
    title: '状态',
    dataIndex: 'state',
    key: 'state',
    render: val => <span>{packetStateDict[val]}</span>,
  },
  {
    title: '备注',
    dataIndex: 'remark',
  },
  {
    title: '最后更新人',
    dataIndex: 'modifyPerson',
  },
  {
    title: '最后更新时间',
    dataIndex: 'modifyTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    title: '创建人',
    dataIndex: 'createPerson',
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];

// 查询条件输入的数据
export const fieldLabelsForm = [
  {
    key: 'code',
    label: '工艺方法编码',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'name',
    label: '工艺方法名称',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'processCode',
    label: '所属工序编码',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    childType: 'key',
    selectArr: [],
  },
  {
    key: 'processName',
    label: '所属工序名称',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'mTargetSampleTypes',
    label: '中间产物类型',
    disabled: false,
    value: '',
    require: false,
    mode: 'multiple',
    type: 'select',
    selectArr: [],
  },
  {
    key: 'fTargetSampleTypeId',
    label: '最终产物类型',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    key: 'remark',
    label: '备注',
    disabled: false,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'operateOrderUrl',
    label: '操作单模板',
    disabled: false,
    value: '',
    require: true,
    type: 'upload',
    selectArr: [],
  },
  {
    key: 'state',
    label: '状态',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: packetStateArr,
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
];
// 查询条件输入的数据(详情)
export const fieldLabelsDetailForm = [
  {
    key: 'code',
    label: '工艺方法编码',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'name',
    label: '工艺方法名称',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'processCode',
    label: '所属工序编码',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    childType: 'key',
    selectArr: [],
  },
  {
    key: 'processName',
    label: '所属工序名称',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'mTargetSampleTypes',
    label: '中间产物类型',
    disabled: false,
    value: '',
    require: false,
    mode: 'multiple',
    type: 'select',
    selectArr: [],
  },
  {
    key: 'fTargetSampleTypeId',
    label: '最终产物类型',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    key: 'remark',
    label: '备注',
    disabled: false,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'operateOrderUrl',
    label: '操作单模板',
    disabled: false,
    value: '',
    require: true,
    type: 'upload',
    selectArr: [],
  },
  {
    key: 'state',
    label: '状态',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: packetStateArr,
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
];
// 工序方法添加界面
export const tableAddColumns = [
  {
    title: '物料编码',
    dataIndex: 'materielCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '商品货号',
    dataIndex: 'productCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '商品名称',
    dataIndex: 'productName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '规格型号',
    dataIndex: 'specType',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '品牌',
    dataIndex: 'brand',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '单位',
    dataIndex: 'unit',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '使用量/单样本',
    dataIndex: 'amountOfSample',
    disabled: false,
    value: '',
    require: true,
    validateType: 'number_2', // 校验类型
    type: 'input',
    selectArr: [],
  },
  {
    title: '使用量/单次实验',
    dataIndex: 'amountOfLab',
    disabled: false,
    value: '',
    require: true,
    validateType: 'number_2', // 校验类型
    type: 'input',
    selectArr: [],
  },
  {
    title: '损耗比例',
    dataIndex: 'consumableProp',
    disabled: false,
    value: '',
    require: true,
    validateType: 'number_2', // 校验类型
    type: 'input',
    selectArr: [],
  },
  {
    title: '使用单位',
    dataIndex: 'useUnit',
    disabled: false,
    value: '',
    require: false,
    mode: '',
    type: 'select',
    selectArr: [],
  },
];
// 工序方法添加界面弹出框
export const tableAddchildMColumns = [
  {
    title: '物料编码',
    dataIndex: 'materielCode',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '商品货号',
    dataIndex: 'productCode',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '商品名称',
    dataIndex: 'productName',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '规格型号',
    dataIndex: 'specType',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '品牌',
    dataIndex: 'brand',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '单位',
    dataIndex: 'unit',
    disabled: true,
    value: 'ul',
    require: false,
    type: 'input',
    selectArr: [],
  },
]

//表格数据
export const tableDetailColumns = [
  {
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '工序方法编码',
    dataIndex: 'code',
  },
  {
    title: '工序方法名称',
    dataIndex: 'name',
  },
  {
    title: '所属工序编码',
    dataIndex: 'processCode',
  },
  {
    title: '所属工序名称',
    dataIndex: 'processName',
  },

  {
    dataIndex: 'middleSampleTypeId',
    title: '中间产物类型',
    disabled: false,
    value: '',
    require: false,
    mode: 'multiple',
    type: 'select',
    selectArr: [],
  },
  {
    dataIndex: 'finallySampleTypeId',
    title: '最终产物类型',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '状态',
    dataIndex: 'state',
    key: 'state',
    render: val => <span>{packetStateDict[val]}</span>,
  },
  {
    title: '备注',
    dataIndex: 'remark',
  },
  {
    title: '最后更新人',
    dataIndex: 'modifyPerson',
  },
  {
    title: '最后更新时间',
    dataIndex: 'modifyTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    title: '创建人',
    dataIndex: 'createPerson',
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];
