// 表格表头的数据检验订单详情的送检单信息
import { handPeriodTypeDict, seqInstrumentArr, seqInstrumentDict, startupTypeArr, startupTypeDict, packetStateArr, whetherArr, experimentContentArr,
   qcTypeArr, qcTypeDict, outDataTypeArr, outDataTypeDict, handPeriodTypeArr, packetStateDict, sampleModeDict, whetherDict } from '@/utils/experimentServiceDict';
import moment from 'moment';
// 首页的
export const tableHomeColumns = [
  {
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '检测包编码',
    key: 'packetCode',
    dataIndex: 'packetCode',
  },
  {
    title: '检测包名称',
    key: 'packetName',
    dataIndex: 'packetName',
  },
  {
    title: '状态',
    dataIndex: 'packetState',
    render: val => <span>{packetStateDict[val]}</span>
  },
  {
    title: '采样方案',
    dataIndex: 'sampleMode',
    render: val => <span>{sampleModeDict[val]}</span>
  },
  {
    title: '组学检测项数',
    dataIndex: 'omicsCount',
  },
  {
    title: '功能医学检测项数',
    dataIndex: 'funcCount',
  },
  {
    title: '生化检测项',
    dataIndex: 'bioCount',
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
  },
  {
    title: '备注',
    dataIndex: 'remark',
  },
  {
    title: '已应用商品数',
    dataIndex: 'appliedCount',
  },
  {
    title: '最后更新人',
    dataIndex: 'modifyPerson',
  },
  {
    title: '最后更新时间',
    dataIndex: 'modifyTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    title: '创建人',
    dataIndex: 'createPerson',
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];

// 添加页输入的数据
export const fieldLabelsForm = [
  {
    key: 'packetCode',
    label: '检测包编码',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'packetName',
    label: '检测包名称',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'handPeriod',
    label: '交付周期',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },{
    label: '交付日类型',
    key: 'handPeriodType',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: handPeriodTypeArr,
  },
  {
    key: 'remark',
    label: '备注',
    disabled: false,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
  },
];
// 新增: 添加组学方案表头
export const tableAddOmicsColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '检测项编码',
    dataIndex: 'experimentCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测项名称',
    dataIndex: 'experimentName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '技术平台',
    dataIndex: 'seqInstrument',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: seqInstrumentArr,
    render: val => <span>{seqInstrumentDict[val]}</span>
  },
  {
    title: '技术路线编码',
    dataIndex: 'routeCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '技术路线名称',
    dataIndex: 'routeName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '数据量',
    dataIndex: 'dataSize',
    disabled: false,
    value: '',
    validateType: 'number_2', // 校验类型
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    title: '优先启动样本类型',
    dataIndex: 'triggerSampleType',
    disabled: false,
    value: '',
    require: true,
    // type: 'select-filter',
    type: 'select-filter',
    filterKey: 'routeStartSampleTypes', // 过滤下拉数组
    selectArr: [],
    //TODO 查询启动样本类型列表
  },
  {
    title: '启动样本类型',
    dataIndex: 'routeStartSampleTypes',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: [],
  },
  {
    title: '启动模式',
    dataIndex: 'startupType',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: startupTypeArr,
  },
  {
    dataIndex: 'createPerson',
    title: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'createTime',
    title: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    dataIndex: 'modifyPerson',
    title: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'modifyTime',
    title: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];
// 新增: 添加组学方案表头弹出框
export const tableAddOmicsColumnsModel = [
  {
    title: '检测项编码',
    dataIndex: 'experimentCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测项名称',
    dataIndex: 'experimentName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '技术平台',
    dataIndex: 'seqInstrument',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: seqInstrumentArr,
    render: val => <span>{seqInstrumentDict[val]}</span>
  },
  {
    title: '下机数据类型',
    dataIndex: 'outDataType',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: outDataTypeArr,
    render: val => <span>{outDataTypeDict[val]}</span>,
    //TODO 查询启动样本类型列表
  },
  {
    title: '技术路线编码',
    dataIndex: 'routeCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '技术路线名称',
    dataIndex: 'routeName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: true,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    disabled: true,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    dataIndex: 'remark',
    title: '备注',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
]
// 新增: 添加功能医学方案表头
export const tableAddFuncColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '检测套餐编码',
    dataIndex: 'packCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测套餐名称',
    dataIndex: 'packName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测项数',
    dataIndex: 'examCount',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: handPeriodTypeArr,
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    title: '启动样本类型',
    dataIndex: 'sampleTypes',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '启动模式',
    dataIndex: 'startupType',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: startupTypeArr,
  },
  {
    dataIndex: 'createPerson',
    title: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'createTime',
    title: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    dataIndex: 'modifyPerson',
    title: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'modifyTime',
    title: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];
// 功能医学检测方案表头弹出框
export const tableAddFuncColumnsModel = [
  {
    title: '检测套餐编码',
    dataIndex: 'packCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测套餐名称',
    dataIndex: 'packName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测项数',
    dataIndex: 'examCount',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '启动样本类型',
    dataIndex: 'sampleTypes',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: handPeriodTypeArr,
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    title: '备注',
    dataIndex: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
]

// 新增: 添加生化方案表头
export const tableAddBioColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '检测套餐编码',
    dataIndex: 'packCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测套餐名称',
    dataIndex: 'packName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '检测项数',
    dataIndex: 'examCount',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '交付日类型',
    dataIndex: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: handPeriodTypeArr,
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    title: '启动样本类型',
    dataIndex: 'sampleTypes',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '启动模式',
    dataIndex: 'startupType',
    disabled: false,
    value: '',
    require: true,
    type: 'select',
    selectArr: startupTypeArr,
  },
  {
    dataIndex: 'createPerson',
    title: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'createTime',
    title: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    dataIndex: 'modifyPerson',
    title: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    dataIndex: 'modifyTime',
    title: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];
// 新增: 添加采样方案表头
export const tableAddBoxColumns = [
  // {
  //   title: '序号',
  //   index: 'index',
  //   render:(text,record,index)=>`${index+1}`,
  // },
  {
    title: '采样盒类型编码',
    dataIndex: 'boxTypeCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '采样盒类型名称',
    dataIndex: 'boxTypeName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '内含采集器数量',
    dataIndex: 'capacityNum',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '备注',
    dataIndex: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    dataIndex: 'createPerson',
    title: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'createTime',
    title: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    dataIndex: 'modifyPerson',
    title: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    dataIndex: 'modifyTime',
    title: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
];
export const tableAddBoxColumnsModel = [
  {
    title: '采样盒类型编码',
    dataIndex: 'boxTypeCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '采样盒类型名称',
    dataIndex: 'boxTypeName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '内含采集器数量',
    dataIndex: 'capacityNum',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    title: '备注',
    dataIndex: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
]
// 详情页的 弹出框详情 组学
export const modelDetailOmics = {
  Arr: [
    {
      key: 'experimentCode',
      label: '检测项编码',
      disabled: true,
      value: '',
      require: false,
      type: 'input',
      selectArr: [],
    },
    {
      key: 'experimentName',
      label: '检测项名称',
      disabled: false,
      value: '',
      require: true,
      type: 'input',
      selectArr: [],
    },
    {
      key: 'routeCode',
      label: '技术路线编码',
      disabled: false,
      value: '',
      require: true,
      type: 'input',
      selectArr: [],
    },
    {
      key: 'routeName',
      label: '技术路线名称',
      disabled: false,
      value: '',
      require: true,
      type: 'input',
      selectArr: [],
    },
    {
      key: 'seqInstrument',
      label: '技术平台',
      disabled: false,
      value: '',
      require: true,
      type: 'select',
      selectArr: seqInstrumentArr,
    },
    {
      key: 'outDataType',
      label: '下机数据类型',
      disabled: false,
      value: '',
      require: true,
      type: 'select',
      selectArr: outDataTypeArr,
    }
  ],
  table: [{
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '是否分包',
    dataIndex: 'outsource',
    disabled: false,
    value: 'false',
    require: true,
    type: 'select',
    selectArr: whetherArr,
    render: val => <span>{whetherDict[val]}</span>,
  },
  {
    title: '工序编号',
    dataIndex: 'code',
    disabled: false,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    title: '工序名称',
    dataIndex: 'name',
    disabled: false,
    value: '',
    require: false,
    type: 'select-input',
    childKey: 'handPeriod', // 级联的关联字段
    selectArr: [],
  },
  {
    title: 'QC检测内容',
    dataIndex: 'qcExamContent',
    disabled: false,
    value: '',
    require: false,
    mode: 'multiple',
    type: 'select',
    selectArr: experimentContentArr,
  },
  // {
  //   title: '中间产物类型',
  //   dataIndex: 'middleSampleTypeId',
  //   disabled: false,
  //   value: '',
  //   require: false,
  //   mode: 'multiple',
  //   type: 'select',
  //   selectArr: [],
  // },
  {
    title: '交付周期',
    dataIndex: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },],
}
// 详情页的 弹出框详情 功能医学方案
export const modelDetailFuncs = {
  Arr: [
    {
    label: '检测套餐编码',
    key: 'packCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '检测套餐名称',
    key: 'packName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '启动样本类型',
    key: 'sampleTypes',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    label: '交付周期',
    key: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    label: '交付日类型',
    key: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    label: '备注',
    key: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  ],
  table: [{
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '检验项目名称',
    dataIndex: 'packName',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },],
}
// 详情页的 弹出框详情 生化检测
export const modelDetailBios = {
  Arr: [
    {
    label: '检测套餐编码',
    key: 'packCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '检测套餐名称',
    key: 'packName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '启动样本类型',
    key: 'sampleTypes',
    disabled: false,
    value: '',
    require: true,
    type: 'input',
    selectArr: [],
  },
  {
    label: '交付周期',
    key: 'handPeriod',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  {
    label: '交付日类型',
    key: 'handPeriodType',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{handPeriodTypeDict[val]}</span>
  },
  {
    key: 'createPerson',
    label: '创建人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    key: 'createTime',
    label: '创建时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    key: 'modifyPerson',
    label: '最后更新人',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    key: 'modifyTime',
    label: '最后更新时间',
    disabled: true,
    value: '',
    require: false,
    type: 'time',
    selectArr: [],
    render: val => <span>{moment(val).format('YYYY-MM-DD HH:mm:ss')}</span>,
  },
  {
    label: '备注',
    key: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },
  ],
  table: [{
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '检验项目名称',
    dataIndex: 'packName',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },],
}
// 详情页的 弹出框详情 采样方案添加采样盒
export const modelDetailBoxes = {
  Arr: [{
    label: '采样盒类型编码',
    key: 'boxTypeCode',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '采样盒类型名称',
    key: 'boxTypeName',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: [],
  },
  {
    label: '是否包含回寄快递单',
    key: 'needCourierReceipt',
    disabled: true,
    value: '',
    require: false,
    type: 'select',
    selectArr: whetherArr,
  },
  {
    label: '备注',
    key: 'remark',
    disabled: true,
    value: '',
    require: false,
    type: 'input',
    selectArr: []
  },],
  table: [{
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '名称',
    dataIndex: 'type',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '数量',
    dataIndex: 'count',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },],
  tableOne: [{
    title: '序号',
    index: 'index',
    render: (text, record, index) => `${index + 1}`,
  },
  {
    title: '名称',
    dataIndex: 'name',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },
  {
    title: '数量',
    dataIndex: 'count',
    disabled: false,
    require: true,
    type: 'select',
    selectArr: [],
  },],
}
